let clicked1 = false;
let clicked2 = false;
let clicked3 = false;
let clicked4 = false;
let clicked5 = false;
let clicked6 = false;
let clicked7 = false;
let clicked8 = false;
let clicked9 = false;
let clicked10 = false;
let clicked11 = false;

$(document).ready(function () {
  $("#show-button").click(function () {
    if (clicked1 == false) {
      $("#button-1").hide();
      $("#button-2").hide();
      $("#button-3").hide();
      $("#button-4").hide();
      $("#button-5").hide();
      $("#button-6").hide();
      $("#button-7").hide();
      $("#button-8").hide();
      $("#button-9").hide();
      $("#button-10").hide();
      $("#button-11").hide();
      $("#button-12").hide();
      $("#button-13").hide();
      $("#button-14").hide();
      $("#button-15").hide();
      $("#button-16").hide();
      $("#button-17").hide();
      $("#button-18").hide();
      $("#button-19").hide();
      $("#button-20").hide();
      $("#button-21").hide();
      $("#button-22").hide();
      $("#button-23").hide();
      $("#button-24").hide();
      $("#button-25").hide();
      $("#button-26").hide();
      $("#button-27").hide();
      $("#button-28").hide();
      $("#button-29").hide();
      $("#button-30").hide();
      $("#button-31").hide();
      $("#button-32").hide();
      $("#button-33").hide();
      $("#button-Blus1").hide();
      $("#button-Blus2").hide();
      $("#button-Blus3").hide();
      $("#button-Blus11").hide();
      $("#button-Blus22").hide();
      $("#button-Blus111").hide();
      $("#button-Blus222").hide();
      $("#button-Blus1111").hide();
      $("#button-Blus2222").hide();
      $("#button-Blus11111").hide();
      $("#button-Blus22222").hide();
      $("#button-Blus33333").hide();
      $("#button-Blus111111").hide();
      $("#button-Blus222222").hide();
      $("#button-Blus333333").hide();
      $("#button-Blus1111111").hide();
      $("#button-Blus2222222").hide();
      $("#button-Blus3333333").hide();
      $("#button-Blus4444444").hide();
      $("#button-Blus5555555").hide();
      $("#button-Blus6666666").hide();
      clicked1 = false;
      clicked2 = false;
      clicked3 = false;
      clicked4 = false;
      clicked5 = false;
      clicked6 = false;
      clicked7 = false;
      clicked8 = false;
      clicked9 = false;
      clicked10 = false;
      clicked11 = false;
      $("#button-1").show();
      $("#button-2").show();
      $("#button-3").show();
      clicked1 = true;
    } else {
      $("#button-1").hide();
      $("#button-2").hide();
      $("#button-3").hide();
      clicked1 = false;
    }
  });

  $("#show-button-2").click(function () {
    if (clicked2 == false) {
      $("#button-1").hide();
      $("#button-2").hide();
      $("#button-3").hide();
      $("#button-4").hide();
      $("#button-5").hide();
      $("#button-6").hide();
      $("#button-7").hide();
      $("#button-8").hide();
      $("#button-9").hide();
      $("#button-10").hide();
      $("#button-11").hide();
      $("#button-12").hide();
      $("#button-13").hide();
      $("#button-14").hide();
      $("#button-15").hide();
      $("#button-16").hide();
      $("#button-17").hide();
      $("#button-18").hide();
      $("#button-19").hide();
      $("#button-20").hide();
      $("#button-21").hide();
      $("#button-22").hide();
      $("#button-23").hide();
      $("#button-24").hide();
      $("#button-25").hide();
      $("#button-26").hide();
      $("#button-27").hide();
      $("#button-28").hide();
      $("#button-29").hide();
      $("#button-30").hide();
      $("#button-31").hide();
      $("#button-32").hide();
      $("#button-33").hide();
      $("#button-Blus1").hide();
      $("#button-Blus2").hide();
      $("#button-Blus3").hide();
      $("#button-Blus11").hide();
      $("#button-Blus22").hide();
      $("#button-Blus111").hide();
      $("#button-Blus222").hide();
      $("#button-Blus1111").hide();
      $("#button-Blus2222").hide();
      $("#button-Blus11111").hide();
      $("#button-Blus22222").hide();
      $("#button-Blus33333").hide();
      $("#button-Blus111111").hide();
      $("#button-Blus222222").hide();
      $("#button-Blus333333").hide();
      $("#button-Blus1111111").hide();
      $("#button-Blus2222222").hide();
      $("#button-Blus3333333").hide();
      $("#button-Blus4444444").hide();
      $("#button-Blus5555555").hide();
      $("#button-Blus6666666").hide();
      clicked1 = false;
      clicked2 = false;
      clicked3 = false;
      clicked4 = false;
      clicked5 = false;
      clicked6 = false;
      clicked7 = false;
      clicked8 = false;
      clicked9 = false;
      clicked10 = false;
      clicked11 = false;
      $("#button-4").show();
      $("#button-5").show();
      $("#button-6").show();
      clicked2 = true;
    } else {
      $("#button-4").hide();
      $("#button-5").hide();
      $("#button-6").hide();
      clicked2 = false;
    }
  });

  $("#show-button-3").click(function () {
    if (clicked3 == false) {
      $("#button-1").hide();
      $("#button-2").hide();
      $("#button-3").hide();
      $("#button-4").hide();
      $("#button-5").hide();
      $("#button-6").hide();
      $("#button-7").hide();
      $("#button-8").hide();
      $("#button-9").hide();
      $("#button-10").hide();
      $("#button-11").hide();
      $("#button-12").hide();
      $("#button-13").hide();
      $("#button-14").hide();
      $("#button-15").hide();
      $("#button-16").hide();
      $("#button-17").hide();
      $("#button-18").hide();
      $("#button-19").hide();
      $("#button-20").hide();
      $("#button-21").hide();
      $("#button-22").hide();
      $("#button-23").hide();
      $("#button-24").hide();
      $("#button-25").hide();
      $("#button-26").hide();
      $("#button-27").hide();
      $("#button-28").hide();
      $("#button-29").hide();
      $("#button-30").hide();
      $("#button-31").hide();
      $("#button-32").hide();
      $("#button-33").hide();
      $("#button-Blus1").hide();
      $("#button-Blus2").hide();
      $("#button-Blus3").hide();
      $("#button-Blus11").hide();
      $("#button-Blus22").hide();
      $("#button-Blus111").hide();
      $("#button-Blus222").hide();
      $("#button-Blus1111").hide();
      $("#button-Blus2222").hide();
      $("#button-Blus11111").hide();
      $("#button-Blus22222").hide();
      $("#button-Blus33333").hide();
      $("#button-Blus111111").hide();
      $("#button-Blus222222").hide();
      $("#button-Blus333333").hide();
      $("#button-Blus1111111").hide();
      $("#button-Blus2222222").hide();
      $("#button-Blus3333333").hide();
      $("#button-Blus4444444").hide();
      $("#button-Blus5555555").hide();
      $("#button-Blus6666666").hide();
      clicked1 = false;
      clicked2 = false;
      clicked3 = false;
      clicked4 = false;
      clicked5 = false;
      clicked6 = false;
      clicked7 = false;
      clicked8 = false;
      clicked9 = false;
      clicked10 = false;
      clicked11 = false;
      $("#button-7").show();
      $("#button-8").show();
      $("#button-9").show();
      clicked3 = true;
    } else {
      $("#button-7").hide();
      $("#button-8").hide();
      $("#button-9").hide();
      clicked3 = false;
    }
  });

  $("#show-button-4").click(function () {
    if (clicked4 == false) {
      $("#button-1").hide();
      $("#button-2").hide();
      $("#button-3").hide();
      $("#button-4").hide();
      $("#button-5").hide();
      $("#button-6").hide();
      $("#button-7").hide();
      $("#button-8").hide();
      $("#button-9").hide();
      $("#button-10").hide();
      $("#button-11").hide();
      $("#button-12").hide();
      $("#button-13").hide();
      $("#button-14").hide();
      $("#button-15").hide();
      $("#button-16").hide();
      $("#button-17").hide();
      $("#button-18").hide();
      $("#button-19").hide();
      $("#button-20").hide();
      $("#button-21").hide();
      $("#button-22").hide();
      $("#button-23").hide();
      $("#button-24").hide();
      $("#button-25").hide();
      $("#button-26").hide();
      $("#button-27").hide();
      $("#button-28").hide();
      $("#button-29").hide();
      $("#button-30").hide();
      $("#button-31").hide();
      $("#button-32").hide();
      $("#button-33").hide();
      $("#button-Blus1").hide();
      $("#button-Blus2").hide();
      $("#button-Blus3").hide();
      $("#button-Blus11").hide();
      $("#button-Blus22").hide();
      $("#button-Blus111").hide();
      $("#button-Blus222").hide();
      $("#button-Blus1111").hide();
      $("#button-Blus2222").hide();
      $("#button-Blus11111").hide();
      $("#button-Blus22222").hide();
      $("#button-Blus33333").hide();
      $("#button-Blus111111").hide();
      $("#button-Blus222222").hide();
      $("#button-Blus333333").hide();
      $("#button-Blus1111111").hide();
      $("#button-Blus2222222").hide();
      $("#button-Blus3333333").hide();
      $("#button-Blus4444444").hide();
      $("#button-Blus5555555").hide();
      $("#button-Blus6666666").hide();
      clicked1 = false;
      clicked2 = false;
      clicked3 = false;
      clicked4 = false;
      clicked5 = false;
      clicked6 = false;
      clicked7 = false;
      clicked8 = false;
      clicked9 = false;
      clicked10 = false;
      clicked11 = false;
      $("#button-10").show();
      $("#button-11").show();
      $("#button-12").show();
      $("#button-Blus1").show();
      $("#button-Blus2").show();
      $("#button-Blus3").show();
      clicked4 = true;
    } else {
      $("#button-10").hide();
      $("#button-11").hide();
      $("#button-12").hide();
      $("#button-Blus1").hide();
      $("#button-Blus2").hide();
      $("#button-Blus3").hide();
      clicked4 = false;
    }
  });

  $("#show-button-5").click(function () {
    if (clicked5 == false) {
      $("#button-1").hide();
      $("#button-2").hide();
      $("#button-3").hide();
      $("#button-4").hide();
      $("#button-5").hide();
      $("#button-6").hide();
      $("#button-7").hide();
      $("#button-8").hide();
      $("#button-9").hide();
      $("#button-10").hide();
      $("#button-11").hide();
      $("#button-12").hide();
      $("#button-13").hide();
      $("#button-14").hide();
      $("#button-15").hide();
      $("#button-16").hide();
      $("#button-17").hide();
      $("#button-18").hide();
      $("#button-19").hide();
      $("#button-20").hide();
      $("#button-21").hide();
      $("#button-22").hide();
      $("#button-23").hide();
      $("#button-24").hide();
      $("#button-25").hide();
      $("#button-26").hide();
      $("#button-27").hide();
      $("#button-28").hide();
      $("#button-29").hide();
      $("#button-30").hide();
      $("#button-31").hide();
      $("#button-32").hide();
      $("#button-33").hide();
      $("#button-Blus1").hide();
      $("#button-Blus2").hide();
      $("#button-Blus3").hide();
      $("#button-Blus11").hide();
      $("#button-Blus22").hide();
      $("#button-Blus111").hide();
      $("#button-Blus222").hide();
      $("#button-Blus1111").hide();
      $("#button-Blus2222").hide();
      $("#button-Blus11111").hide();
      $("#button-Blus22222").hide();
      $("#button-Blus33333").hide();
      $("#button-Blus111111").hide();
      $("#button-Blus222222").hide();
      $("#button-Blus333333").hide();
      $("#button-Blus1111111").hide();
      $("#button-Blus2222222").hide();
      $("#button-Blus3333333").hide();
      $("#button-Blus4444444").hide();
      $("#button-Blus5555555").hide();
      $("#button-Blus6666666").hide();
      clicked1 = false;
      clicked2 = false;
      clicked3 = false;
      clicked4 = false;
      clicked5 = false;
      clicked6 = false;
      clicked7 = false;
      clicked8 = false;
      clicked9 = false;
      clicked10 = false;
      clicked11 = false;
      $("#button-13").show();
      $("#button-14").show();
      $("#button-15").show();
      clicked5 = true;
    } else {
      $("#button-13").hide();
      $("#button-14").hide();
      $("#button-15").hide();
      clicked5 = false;
    }
  });

  $("#show-button-6").click(function () {
    if (clicked6 == false) {
      $("#button-1").hide();
      $("#button-2").hide();
      $("#button-3").hide();
      $("#button-4").hide();
      $("#button-5").hide();
      $("#button-6").hide();
      $("#button-7").hide();
      $("#button-8").hide();
      $("#button-9").hide();
      $("#button-10").hide();
      $("#button-11").hide();
      $("#button-12").hide();
      $("#button-13").hide();
      $("#button-14").hide();
      $("#button-15").hide();
      $("#button-16").hide();
      $("#button-17").hide();
      $("#button-18").hide();
      $("#button-19").hide();
      $("#button-20").hide();
      $("#button-21").hide();
      $("#button-22").hide();
      $("#button-23").hide();
      $("#button-24").hide();
      $("#button-25").hide();
      $("#button-26").hide();
      $("#button-27").hide();
      $("#button-28").hide();
      $("#button-29").hide();
      $("#button-30").hide();
      $("#button-31").hide();
      $("#button-32").hide();
      $("#button-33").hide();
      $("#button-Blus1").hide();
      $("#button-Blus2").hide();
      $("#button-Blus3").hide();
      $("#button-Blus11").hide();
      $("#button-Blus22").hide();
      $("#button-Blus111").hide();
      $("#button-Blus222").hide();
      $("#button-Blus1111").hide();
      $("#button-Blus2222").hide();
      $("#button-Blus11111").hide();
      $("#button-Blus22222").hide();
      $("#button-Blus33333").hide();
      $("#button-Blus111111").hide();
      $("#button-Blus222222").hide();
      $("#button-Blus333333").hide();
      $("#button-Blus1111111").hide();
      $("#button-Blus2222222").hide();
      $("#button-Blus3333333").hide();
      $("#button-Blus4444444").hide();
      $("#button-Blus5555555").hide();
      $("#button-Blus6666666").hide();
      clicked1 = false;
      clicked2 = false;
      clicked3 = false;
      clicked4 = false;
      clicked5 = false;
      clicked6 = false;
      clicked7 = false;
      clicked8 = false;
      clicked9 = false;
      clicked10 = false;
      clicked11 = false;
      $("#button-16").show();
      $("#button-17").show();
      $("#button-18").show();
      $("#button-Blus11").show();
      $("#button-Blus22").show();

      clicked6 = true;
    } else {
      $("#button-16").hide();
      $("#button-17").hide();
      $("#button-18").hide();
      $("#button-Blus11").hide();
      $("#button-Blus22").hide();
      clicked6 = false;
    }
  });

  $("#show-button-7").click(function () {
    if (clicked7 == false) {
      $("#button-1").hide();
      $("#button-2").hide();
      $("#button-3").hide();
      $("#button-4").hide();
      $("#button-5").hide();
      $("#button-6").hide();
      $("#button-7").hide();
      $("#button-8").hide();
      $("#button-9").hide();
      $("#button-10").hide();
      $("#button-11").hide();
      $("#button-12").hide();
      $("#button-13").hide();
      $("#button-14").hide();
      $("#button-15").hide();
      $("#button-16").hide();
      $("#button-17").hide();
      $("#button-18").hide();
      $("#button-19").hide();
      $("#button-20").hide();
      $("#button-21").hide();
      $("#button-22").hide();
      $("#button-23").hide();
      $("#button-24").hide();
      $("#button-25").hide();
      $("#button-26").hide();
      $("#button-27").hide();
      $("#button-28").hide();
      $("#button-29").hide();
      $("#button-30").hide();
      $("#button-31").hide();
      $("#button-32").hide();
      $("#button-33").hide();
      $("#button-Blus1").hide();
      $("#button-Blus2").hide();
      $("#button-Blus3").hide();
      $("#button-Blus11").hide();
      $("#button-Blus22").hide();
      $("#button-Blus111").hide();
      $("#button-Blus222").hide();
      $("#button-Blus1111").hide();
      $("#button-Blus2222").hide();
      $("#button-Blus11111").hide();
      $("#button-Blus22222").hide();
      $("#button-Blus33333").hide();
      $("#button-Blus111111").hide();
      $("#button-Blus222222").hide();
      $("#button-Blus333333").hide();
      $("#button-Blus1111111").hide();
      $("#button-Blus2222222").hide();
      $("#button-Blus3333333").hide();
      $("#button-Blus4444444").hide();
      $("#button-Blus5555555").hide();
      $("#button-Blus6666666").hide();
      clicked1 = false;
      clicked2 = false;
      clicked3 = false;
      clicked4 = false;
      clicked5 = false;
      clicked6 = false;
      clicked7 = false;
      clicked8 = false;
      clicked9 = false;
      clicked10 = false;
      clicked11 = false;
      $("#button-19").show();
      $("#button-20").show();
      $("#button-21").show();
      $("#button-Blus111").show();
      $("#button-Blus222").show();
      clicked7 = true;
    } else {
      $("#button-19").hide();
      $("#button-20").hide();
      $("#button-21").hide();
      $("#button-Blus111").hide();
      $("#button-Blus222").hide();
      clicked7 = false;
    }
  });

  $("#show-button-8").click(function () {
    if (clicked8 == false) {
      $("#button-1").hide();
      $("#button-2").hide();
      $("#button-3").hide();
      $("#button-4").hide();
      $("#button-5").hide();
      $("#button-6").hide();
      $("#button-7").hide();
      $("#button-8").hide();
      $("#button-9").hide();
      $("#button-10").hide();
      $("#button-11").hide();
      $("#button-12").hide();
      $("#button-13").hide();
      $("#button-14").hide();
      $("#button-15").hide();
      $("#button-16").hide();
      $("#button-17").hide();
      $("#button-18").hide();
      $("#button-19").hide();
      $("#button-20").hide();
      $("#button-21").hide();
      $("#button-22").hide();
      $("#button-23").hide();
      $("#button-24").hide();
      $("#button-25").hide();
      $("#button-26").hide();
      $("#button-27").hide();
      $("#button-28").hide();
      $("#button-29").hide();
      $("#button-30").hide();
      $("#button-31").hide();
      $("#button-32").hide();
      $("#button-33").hide();
      $("#button-Blus1").hide();
      $("#button-Blus2").hide();
      $("#button-Blus3").hide();
      $("#button-Blus11").hide();
      $("#button-Blus22").hide();
      $("#button-Blus111").hide();
      $("#button-Blus222").hide();
      $("#button-Blus1111").hide();
      $("#button-Blus2222").hide();
      $("#button-Blus11111").hide();
      $("#button-Blus22222").hide();
      $("#button-Blus33333").hide();
      $("#button-Blus111111").hide();
      $("#button-Blus222222").hide();
      $("#button-Blus333333").hide();
      $("#button-Blus1111111").hide();
      $("#button-Blus2222222").hide();
      $("#button-Blus3333333").hide();
      $("#button-Blus4444444").hide();
      $("#button-Blus5555555").hide();
      $("#button-Blus6666666").hide();
      clicked1 = false;
      clicked2 = false;
      clicked3 = false;
      clicked4 = false;
      clicked5 = false;
      clicked6 = false;
      clicked7 = false;
      clicked8 = false;
      clicked9 = false;
      clicked10 = false;
      clicked11 = false;
      $("#button-22").show();
      $("#button-23").show();
      $("#button-24").show();
      $("#button-Blus1111").show();
      $("#button-Blus2222").show();
      clicked8 = true;
    } else {
      $("#button-22").hide();
      $("#button-23").hide();
      $("#button-24").hide();
      $("#button-Blus1111").hide();
      $("#button-Blus2222").hide();
      clicked8 = false;
    }
  });

  $("#show-button-9").click(function () {
    if (clicked9 == false) {
      $("#button-1").hide();
      $("#button-2").hide();
      $("#button-3").hide();
      $("#button-4").hide();
      $("#button-5").hide();
      $("#button-6").hide();
      $("#button-7").hide();
      $("#button-8").hide();
      $("#button-9").hide();
      $("#button-10").hide();
      $("#button-11").hide();
      $("#button-12").hide();
      $("#button-13").hide();
      $("#button-14").hide();
      $("#button-15").hide();
      $("#button-16").hide();
      $("#button-17").hide();
      $("#button-18").hide();
      $("#button-19").hide();
      $("#button-20").hide();
      $("#button-21").hide();
      $("#button-22").hide();
      $("#button-23").hide();
      $("#button-24").hide();
      $("#button-25").hide();
      $("#button-26").hide();
      $("#button-27").hide();
      $("#button-28").hide();
      $("#button-29").hide();
      $("#button-30").hide();
      $("#button-31").hide();
      $("#button-32").hide();
      $("#button-33").hide();
      $("#button-Blus1").hide();
      $("#button-Blus2").hide();
      $("#button-Blus3").hide();
      $("#button-Blus11").hide();
      $("#button-Blus22").hide();
      $("#button-Blus111").hide();
      $("#button-Blus222").hide();
      $("#button-Blus1111").hide();
      $("#button-Blus2222").hide();
      $("#button-Blus11111").hide();
      $("#button-Blus22222").hide();
      $("#button-Blus33333").hide();
      $("#button-Blus111111").hide();
      $("#button-Blus222222").hide();
      $("#button-Blus333333").hide();
      $("#button-Blus1111111").hide();
      $("#button-Blus2222222").hide();
      $("#button-Blus3333333").hide();
      $("#button-Blus4444444").hide();
      $("#button-Blus5555555").hide();
      $("#button-Blus6666666").hide();
      clicked1 = false;
      clicked2 = false;
      clicked3 = false;
      clicked4 = false;
      clicked5 = false;
      clicked6 = false;
      clicked7 = false;
      clicked8 = false;
      clicked9 = false;
      clicked10 = false;
      clicked11 = false;
      $("#button-25").show();
      $("#button-26").show();
      $("#button-27").show();
      $("#button-Blus11111").show();
      $("#button-Blus22222").show();
      $("#button-Blus33333").show();
      clicked9 = true;
    } else {
      $("#button-25").hide();
      $("#button-26").hide();
      $("#button-27").hide();
      $("#button-Blus11111").hide();
      $("#button-Blus22222").hide();
      $("#button-Blus33333").hide();
      clicked9 = false;
    }
  });

  $("#show-button-10").click(function () {
    if (clicked10 == false) {
      $("#button-1").hide();
      $("#button-2").hide();
      $("#button-3").hide();
      $("#button-4").hide();
      $("#button-5").hide();
      $("#button-6").hide();
      $("#button-7").hide();
      $("#button-8").hide();
      $("#button-9").hide();
      $("#button-10").hide();
      $("#button-11").hide();
      $("#button-12").hide();
      $("#button-13").hide();
      $("#button-14").hide();
      $("#button-15").hide();
      $("#button-16").hide();
      $("#button-17").hide();
      $("#button-18").hide();
      $("#button-19").hide();
      $("#button-20").hide();
      $("#button-21").hide();
      $("#button-22").hide();
      $("#button-23").hide();
      $("#button-24").hide();
      $("#button-25").hide();
      $("#button-26").hide();
      $("#button-27").hide();
      $("#button-28").hide();
      $("#button-29").hide();
      $("#button-30").hide();
      $("#button-31").hide();
      $("#button-32").hide();
      $("#button-33").hide();
      $("#button-Blus1").hide();
      $("#button-Blus2").hide();
      $("#button-Blus3").hide();
      $("#button-Blus11").hide();
      $("#button-Blus22").hide();
      $("#button-Blus111").hide();
      $("#button-Blus222").hide();
      $("#button-Blus1111").hide();
      $("#button-Blus2222").hide();
      $("#button-Blus11111").hide();
      $("#button-Blus22222").hide();
      $("#button-Blus33333").hide();
      $("#button-Blus111111").hide();
      $("#button-Blus222222").hide();
      $("#button-Blus333333").hide();
      $("#button-Blus1111111").hide();
      $("#button-Blus2222222").hide();
      $("#button-Blus3333333").hide();
      $("#button-Blus4444444").hide();
      $("#button-Blus5555555").hide();
      $("#button-Blus6666666").hide();
      clicked1 = false;
      clicked2 = false;
      clicked3 = false;
      clicked4 = false;
      clicked5 = false;
      clicked6 = false;
      clicked7 = false;
      clicked8 = false;
      clicked9 = false;
      clicked10 = false;
      clicked11 = false;
      $("#button-28").show();
      $("#button-29").show();
      $("#button-30").show();
      $("#button-Blus111111").show();
      $("#button-Blus222222").show();
      $("#button-Blus333333").show();
      clicked10 = true;
    } else {
      $("#button-28").hide();
      $("#button-29").hide();
      $("#button-30").hide();
      $("#button-Blus111111").hide();
      $("#button-Blus222222").hide();
      $("#button-Blus333333").hide();
      clicked10 = false;
    }
  });

  $("#show-button-11").click(function () {
    if (clicked11 == false) {
      $("#button-1").hide();
      $("#button-2").hide();
      $("#button-3").hide();
      $("#button-4").hide();
      $("#button-5").hide();
      $("#button-6").hide();
      $("#button-7").hide();
      $("#button-8").hide();
      $("#button-9").hide();
      $("#button-10").hide();
      $("#button-11").hide();
      $("#button-12").hide();
      $("#button-13").hide();
      $("#button-14").hide();
      $("#button-15").hide();
      $("#button-16").hide();
      $("#button-17").hide();
      $("#button-18").hide();
      $("#button-19").hide();
      $("#button-20").hide();
      $("#button-21").hide();
      $("#button-22").hide();
      $("#button-23").hide();
      $("#button-24").hide();
      $("#button-25").hide();
      $("#button-26").hide();
      $("#button-27").hide();
      $("#button-28").hide();
      $("#button-29").hide();
      $("#button-30").hide();
      $("#button-31").hide();
      $("#button-32").hide();
      $("#button-33").hide();
      $("#button-Blus1").hide();
      $("#button-Blus2").hide();
      $("#button-Blus3").hide();
      $("#button-Blus11").hide();
      $("#button-Blus22").hide();
      $("#button-Blus111").hide();
      $("#button-Blus222").hide();
      $("#button-Blus1111").hide();
      $("#button-Blus2222").hide();
      $("#button-Blus11111").hide();
      $("#button-Blus22222").hide();
      $("#button-Blus33333").hide();
      $("#button-Blus111111").hide();
      $("#button-Blus222222").hide();
      $("#button-Blus333333").hide();
      $("#button-Blus1111111").hide();
      $("#button-Blus2222222").hide();
      $("#button-Blus3333333").hide();
      $("#button-Blus4444444").hide();
      $("#button-Blus5555555").hide();
      $("#button-Blus6666666").hide();
      clicked1 = false;
      clicked2 = false;
      clicked3 = false;
      clicked4 = false;
      clicked5 = false;
      clicked6 = false;
      clicked7 = false;
      clicked8 = false;
      clicked9 = false;
      clicked10 = false;
      clicked11 = false;
      $("#button-31").show();
      $("#button-32").show();
      $("#button-33").show();
      $("#button-Blus1111111").show();
      $("#button-Blus2222222").show();
      $("#button-Blus3333333").show();
      $("#button-Blus4444444").show();
      $("#button-Blus5555555").show();
      $("#button-Blus6666666").show();
      clicked11 = true;
    } else {
      $("#button-31").hide();
      $("#button-32").hide();
      $("#button-33").hide();
      $("#button-Blus1111111").hide();
      $("#button-Blus2222222").hide();
      $("#button-Blus3333333").hide();
      $("#button-Blus4444444").hide();
      $("#button-Blus5555555").hide();
      $("#button-Blus6666666").hide();
      clicked11 = false;
    }
  });

  $("#hide-button").click(function () {
    /* $("#show-button").show()
    $("#hide-button").hide() */
  });
});

$("#button-Blus1111").hide();
$("#button-Blus2222").hide();
$("#button-Blus11111").hide();
$("#button-Blus22222").hide();
$("#button-Blus33333").hide();
$("#button-Blus111111").hide();
$("#button-Blus222222").hide();
$("#button-Blus333333").hide();
$("#button-Blus1111111").hide();
$("#button-Blus2222222").hide();
$("#button-Blus3333333").hide();
$("#button-Blus4444444").hide();
$("#button-Blus5555555").hide();
$("#button-Blus6666666").hide();
